logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
